apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: wordpress
  namespace: cep-project1
  labels: 
    app: wordpress 
spec: 
  replicas: 1
  selector: 
    matchLabels:
        app: wordpress 
  template: 
    metadata:
      labels:
        app: wordpress 
    spec: 
      containers: 
        - name: wordpress 
          image: wordpress
          env: 
            - name: WORDPRESS_DB_HOST 
              valueFrom: 
                configMapKeyRef: 
                  name: wordpress-config 
                  key: WORDPRESS_DB_HOST
            - name: WORDPRESS_DB_USER 
              valueFrom: 
                configMapKeyRef: 
                  name: wordpress-config 
                  key: WORDPRESS_DB_USER
            - name: WORDPRESS_DB_PASSWORD 
              valueFrom: 
                secretKeyRef: 
                  name: mysql-secret 
                  key: mysql-root-password
            - name: WORDPRESS_DB_NAME 
              valueFrom: 
                secretKeyRef: 
                  name: mysql-secret
                  key: mysql-database
          volumeMounts: 
            - name: wordpress-storage
              mountPath: /var/www/html
      volumes: 
        - name: wordpress-storage 
          persistentVolumeClaim: 
            claimName: wordpress-pvc
---
apiVersion: v1 
kind: Service 
metadata: 
  name: wordpress 
  namespace: cep-project1
spec: 
  ports: 
    - port: 80
      protocol: TCP 
      targetPort: 80 
  selector: 
    app: wordpress 
  type: NodePort
