apiVersion: v1 
kind: Pod 
metadata: 
  name: multi-cont-pod 
spec: 
  containers:
    - name: alpha
      image: nginx 
      env: 
        - name: name
          value: alpha
    - name: beta 
      image: busybox
      command: 
        - sh
        - -c
        - sleep 4800 
      env: 
        - name: name
          value: beta 

