apiVersion: v1 
kind: Pod 
metadata: 
  name: mysql 
spec: 
  containers:
    - name: mysql 
      image: mysql:5.7 
      env: 
        - name: MYSQL_ROOT_PASSWORD
          value: rootroot
        - name: MYSQL_PASSWORD
          value: rootroot
        - name: MYSQL_DATABASE
          value: test
