apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: mysql
  namespace: cep-project1
  labels: 
    app: mysql
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: mysql 
  template: 
    metadata: 
      labels: 
        app: mysql 
    spec: 
      containers: 
        - name: mysql 
          image: mysql:5.6 
          env: 
          - name: MYSQL_ROOT_PASSWORD 
            valueFrom: 
              secretKeyRef: 
                name: mysql-secret 
                key: mysql-root-password
          - name: MYSQL_DATABASE 
            valueFrom: 
              secretKeyRef: 
                name: mysql-secret
                key: mysql-database
          volumeMounts: 
          - name: mysql-storage
            mountPath: /var/lib/mysql 
      volumes: 
        - name: mysql-storage 
          persistentVolumeClaim: 
            claimName: mysql-pvc
--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: mysql 
  namespace: cep-project1
  labels: 
    app: mysql 
spec: 
  ports: 
    - port: 3306 
      protocol: TCP 
      targetPort: 3306 
  selector: 
    app: mysql 
  type: NodePort