apiVersion: v1 
kind: PersistentVolume 
metadata: 
  name: mysql-pv 
  labels: 
    type: mysql-storage
spec: 
  capacity:
    storage: 1Gi 
  accessModes: 
    - ReadWriteOnce
  nfs: 
    path: /mnt/nfs-share/mysql
    server: 172.31.26.110
---
apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
  name: mysql-pvc 
  namespace: cep-project1
spec: 
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 1Gi
  selector: 
    matchLabels: 
      type: mysql-storage
  