apiVersion: v1 
kind: PersistentVolume 
metadata: 
  name: wordpress-pv 
  labels: 
    type: wordpress-storage 
spec: 
  capacity:
    storage: 1Gi 
  accessModes: 
    - ReadWriteOnce
  nfs:
    path: /mnt/nfs-share/wordpress
    server: 172.31.26.110
--- 
apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
  name: wordpress-pvc 
  namespace: cep-project1
spec: 
  accessModes: 
    - ReadWriteOnce 
  resources: 
    requests: 
      storage: 1Gi
  selector: 
    matchLabels: 
      type: wordpress-storage  
