apiVersion: v1 
kind: Pod 
metadata: 
  name: mysql-pod 
  namespace: beta 
spec: 
  containers:
    - name: mysql
      image: mysql:5.6
      imagePullPolicy: IfNotPresent 
      ports: 
        - containerPort: 3306 
          protocol: TCP 
---
apiVersion: v1 
kind: Service 
metadata: 
  name: mysql-service 
  namespace: beta
spec: 
  ports: 
    - port: 
