---
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  creationTimestamp: null 
  labels: 
    app: wordpress 
  name: wordpress 
spec: 
  replicas: 1 
  selector: 
    matchLabels:
      app: wordpress 
  strategy: {}
  template: 
    metadata: 
      labels: 
        app: wordpress 
    spec: 
      containers: 
        - image: wordpress
          name: wordpress 
          env: 
            - name: WORDPRESS_DB_HOST
              value: mysql 
            - name: WORDPRESS_DB_PASSWORD
              value: simplilearn 
            - name: WORDPRESS_DB_USER 
              value: root 
            - name: WORDPRESS_DB_NAME 
              value: database1 
          resources: {}
status: {}

---
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: mysql
  creationTimestamp: null 
  labels: 
    app: mysql 
spec: 
  replicas: 1 
  selector: 
    matchLabels:
      app: mysql 
  strategy: {}
  template: 
    metadata:
      creationTimestamp: null 
      labels: 
        app: mysql 
    spec: 
      containers: 
        - image: mysql:5.6 
          name: mysql 
          env: 
            - name: MYSQL_ROOT_PASSWORD 
              value: simplilearn 
            - name: MYSQL_DATABASE
              value: database1 
          resources: {}
status: {}          

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  type: NodePort
  
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: wordpress
  type: NodePort
