apiVersion: rbac.authorization.k8s.io/v1 
kind: Role 
metadata: 
  name: user1-role 
  namespace: simplilearn 
rules: 
  - apiGroups: ["", "extensions", "apps"]
    resources: ["*"]
    verbs: ["get","list","watch","create","update","patch","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1 
kind: Role 
metadata: 
  name: user2-role 
  namespace: simplilearn 
rules: 
  - apiGroups: ["", "extensions", "apps"]
    resources: ["*"]
    verbs: ["get","list","watch"]
