apiVersion: v1 
kind: Pod 
metadata: 
  name: webapp 
spec: 
  containers: 
    - name: event-simulator
      image: nginx
      volumeMounts: 
        - name: log-volume 
          mountPath: /log 
  volumes: 
    - name: log-volume 
      hostPath: 
        path: /var/log 
        type: Directory 
