apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-waitforconsumer
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 5Gi
