apiVersion: storage.k8s.io/v1
kind: StorageClass 
metadata:
  name: managed-premium-01 
  labels: 
    addonmanager.kubernetes.io/mode: EnsureExists
    kubernetes.io/cluster-service: "true"
  resourceVersion: "391"
  uid: 08be1a5c-7fcf-4603-91eb-354e2fe27fa3 
parameters: 
  cachingMode: ReadOnly 
  kind: Managed 
  storageAccountType: Premium_LRS
provisioner: disk.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: Immediate 
