apiVersion: v1
kind: ConfigMap 
metadata: 
  name: game-demo
data: 
  player_initial_lives: "4"
  ui_properties_file_name: "user-interface.properties"

  game.properties: |
    enemy.types=aliens,monsters
    players.maximum-lives=5
  user-interface.properties: | 
    color.good=purple 
    color.bad=yellow 
    allow.textmode=true
