apiVersion: v1 
kind: Pod 
metadata: 
  name: purple 

spec: 
  containers:
    - name: purple-container 
      image: busybox:1.28 
      command: 
        - sh 
        - -c 
        - echo The app is running! && sleep 3600 
  # Adding 2 init containers to execute sleep commands 
  initContainers: 
    - name: warm-up-1 
      image: busybox:1.28 
      command: ["sh", "-c", "sleep 60"]
    - name: warm-up-2 
      image: busybox:1.28 
      command: ["sh", "-c", "sleep 120"]