apiVersion: v1
kind: Pod 
metadata: 
  name: multi-container-pod
spec: 
  containers:
    - name: web
      image: httpd 
      ports: 
        - containerPort: 80
    
    - name: rexdis 
      image: redis