apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: configmap-deployment 
spec: 
  replicas: 5
  selector: 
    matchLabels: 
      app: dapi-test 
  template: 
    metadata: 
      labels: 
        app: dapi-test
    spec: 
      containers: 
        - name: test-container
          image: gcr.io/google-samples/node-hello:1.0 
          envFrom: 
            - configMapRef: 
                name: game-demo
