apiVersion: v1 
kind: PersistentVolume 
metadata: 
  name: mysql-pv 
  labels: 
    type: mysql-storage
spec: 
  capacity:
    storage: 1Gi 
  accessModes: 
    - ReadWriteOnce
  nfs: 
    path: /mnt/nfs-share/mysql
    server: 192.168.1.10
---
apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
  name: mysql-pvc 
spec: 
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 1Gi
  selector: 
    matchLabels: 
      type: mysql-storage
  