apiVersion: apps/v1
kind: Deployment
metadata:
  name: wegotan-oomer
spec:
  selector:
    matchLabels:
      app: oomer
  replicas: 1
  template:
    metadata:
      labels:
        app: oomer
    spec:
      containers:
        - name: greedymuch
          image: centos:7
          command:
            - sh
            - '-c'
            - "sleep 5 && yes | tr \\n x | head -c 400m | grep n && sleep 1000"
          resources:
            limits:
              memory: 900M
        - name: shell
          image: centos:7
          command:
            - sh
            - '-c'
            - sleep 1000
